
[package]
name = "bevy_dev_console"
version = "0.1.0"
edition = "2021"
exclude = ["assets/", "docs/", ".github/"]
keywords = ["bevy", "console", "development", "source"]
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["builtin-parser", "completions", "builtin-parser-completions"]

completions = []

builtin-parser-completions = [
    "completions",
    "builtin-parser",
    "dep:fuzzy-matcher",
]

builtin-parser = ["dep:logos", "dep:variadics_please", "dep:kinded"]

[dependencies]
bevy = { version = "0.18.1", default-features = false, features = [
    "bevy_color",
    "bevy_log",
] }
bevy_egui = "0.39.1"
chrono = "0.4.44"
tracing-log = "0.2.0"
web-time = "1.1.0"
winit = "0.30.13"
nu-ansi-term = "0.50.3"
ansitok = "0.3.0"

# builtin-parser features
logos = { version = "0.16.0", optional = true }
fuzzy-matcher = { version = "0.3.7", optional = true }
variadics_please = { version = "1.1.0", optional = true }
kinded = { version = "0.5.0", optional = true }

[dev-dependencies]
bevy = { version = "0.18.1", default-features = false, features = ["2d"] }

[lints]
clippy.useless_format = "allow"
rust.missing_docs = "warn"
